### ISSUE TITLE
Sign up issue

### ISSUE THREAD

**Issue by Ameenaadel** [husseinalkoosh/Anamehanii_project#11]
No onboarding, no choosing language, the first screen is just to enter mobile number and follow the registration steps, i followed the steps (all in english), and at the step of choosing my location, it asked me if i can allow the app to access my location and then it freezes and went out of the app, when i opened the app again it started from the first step and it freezes at the same step.

**Comment by mahmooooud** [comment]
onboarding and choosing language screen  ,appear for one time

**Comment by mahmooooud** [comment]
you can clear app data and try again

**Comment by Ameenaadel** [comment]
> onboarding and choosing language screen ,appear for one time

it was the first time after installing app

**Comment by Ameenaadel** [comment]
> you can clear app data and try

You installed the app for me (ios), please if you have time reinstall it for me

**Comment by mahmooooud** [comment]
of course
