### ISSUE TITLE
Provider App: 1 star rating 

### ISSUE THREAD

**Issue by monabahrawy** [husseinalkoosh/Anamehanii_project#2]
Provider Profile Screen> 1-star rating is displayed when there's no rating given to the worker. it will leave bad impression to clients viewing his profile.
![Screenshot_20190909_123805_com example anamehani2](https://user-images.githubusercontent.com/55086861/64524413-bca58100-d2fe-11e9-9725-7512679ed6d8.jpg)

**Comment by monabahrawy** [comment]
also The orientation of Good morning and Premium Plan text is disoriented

**Comment by mahmooooud** [comment]
@monabahrawy
