### ISSUE TITLE
Customer App: The confirm message did not reach me

### ISSUE THREAD

**Issue by heshambarakat** [husseinalkoosh/Anamehanii_project#6]
The confirmation message did not reach me and the application does this oddly every time.
[Please watch the video ](https://drive.google.com/file/d/1-NCiITVnEmQDcKW5HYEeKjGzeW1CyVsu/view?usp=drivesdk)

**Comment by mohamedmaged** [comment]
hesham this might be because your phone number already has been used multiple times on the same project provide me with your phone number so i can make you a static confirmation code

**Comment by mohamedmaged** [comment]
@heshambarakat  this issue will be closed
