### ISSUE TITLE
Provider app : notification hours are so big

### ISSUE THREAD

**Issue by mohamedmaged** [husseinalkoosh/Anamehanii_project#9]
![Screenshot_2019-09-22-18-25-59-070_com anaprovider anamehani2](https://user-images.githubusercontent.com/17501040/65391221-f2b71c00-dd66-11e9-95d4-b5ae96997976.png)
Hours should be transformed to days when exceeding 24 hours

**Comment by mahmooooud** [comment]
This date is fixed 
Because created date in database it was null
